### ISSUE TITLE
should we add limitSymbolsToIncludedHeaders to the cpp_properties.json?

### ISSUE THREAD

**Issue by miltoncandelero** [boocs/ue4-intellisense-fixes#2]
Hello, I tried to see what you do with that variable and I can't make head or tails of the source of the plugin 😅 

Do you know if it would be better to limit this?

An example of what I say we could add:
![image](https://user-images.githubusercontent.com/15253010/112188764-09e7fb80-8be2-11eb-974c-cf218ac8fcdb.png)

**Comment by boocs** [comment]
No, you don't need to!

This extension already checks to see if you need this setting set.

By default limitSymbolsToIncludedHeaders is set to true. So if you don't have this set to false somewhere in the 3 user/folder/workspace configs then the extension won't bother adding it.

limitSymbolsToIncludedHeaders is also why the extension sets the browse.path in the UE4 workspace to [ ]. The setting won't be as efficient otherwise.
