### ISSUE TITLE
Add support for C++20

### ISSUE THREAD

**Issue by Vivraan** [boocs/ue4-intellisense-fixes#20]
A lot of tools and plugins now support various features such as coroutines, so adding the C++20 standard option will help work with those!

**Comment by boocs** [comment]
Ok, I'll try to release it tonight.

**Comment by boocs** [comment]
I'm not sure what to do about the error message I give to UE5 projects. If it's not set to c++17 I give a error. 

I don't want new developers to choose c++20 and use c++20 code. Intellisense wont error but when they try to build it will error since the build will still be using c++17.

Maybe I'll just leave the error message and people who use c++20 can just ignore it.

**Comment by boocs** [comment]
I released 3.1.3 with c++20 support.
