### ISSUE TITLE
Errors opening console when opening any file

### ISSUE THREAD

**Issue by T3kla** [boocs/ue4-intellisense-fixes#28]
So if I open whatever kind of file in VSCode, this error will always appear. I wouldn't mind it appearing if it wasn't for the fact that it brings up the console every time, and every time I have to close it.

![image](https://user-images.githubusercontent.com/23636548/218313752-7fa329f9-957c-42d4-819a-bff0346a6d37.png)

**Comment by boocs** [comment]
Yeah I was aware of this but VSCode let me be lazy because you can just disable the extension globally and then just enable it only for Unreal project workspaces.
![image](https://user-images.githubusercontent.com/62588629/218339110-fb7d932c-26cc-42c8-ae8d-a6354d6c4a80.png)

It should be an easy fix though. I'll look to see if I can fix it. 

It'll be low priority because I'm trying to get this Unreal Clangd extension released in a beta state. I'm also gonna try creating another unreal extension that's been needed.

**Comment by boocs** [comment]
I realized I needed to do the same thing for my Unreal Clangd extension that's releasing soon. I've updated the extension to fix this issue!
