### ISSUE TITLE
'CoreMinimal.h' file not found

### ISSUE THREAD

**Issue by turkeys-cyber** [boocs/ue4-intellisense-fixes#30]
I generated the visual studio project for UE5.2 on my M1. Even when I used the plugin, I kept seeing that the 'CoreMinimal.h' file was not found, but the plugin showed no errors in the ternimal.

**Comment by turkeys-cyber** [comment]
I tried your method, but it didn't work out.
![Screenshot 2023-10-17 at 10 52 17](https://github.com/boocs/ue4-intellisense-fixes/assets/49188473/7eb1c57c-04e2-403f-b3e4-9187554c9df8)
![Screenshot 2023-10-17 at 10 54 02](https://github.com/boocs/ue4-intellisense-fixes/assets/49188473/6d88fc06-919f-47e1-97eb-193c091a8bad)
![Screenshot 2023-10-17 at 10 54 41](https://github.com/boocs/ue4-intellisense-fixes/assets/49188473/108bd30d-01b3-487c-821e-0ec53516e955)

**Comment by turkeys-cyber** [comment]
The code in my engine workspace also complier errors.
![Screenshot 2023-10-17 at 10 55 44](https://github.com/boocs/ue4-intellisense-fixes/assets/49188473/51b9272e-1a9b-4fa3-99d1-9789b56271fc)
![Screenshot 2023-10-17 at 10 56 44](https://github.com/boocs/ue4-intellisense-fixes/assets/49188473/a06a09ae-a877-48cf-b3c0-093f790d6fe6)

**Comment by boocs** [comment]
Someone else had this problem and we couldn't figure it out. Just know that any Unreal Source file will probably have errors because Unreal projects don't properly setup Unreal Source Code files for Intellisense. 

As for you project files having CoreMinimal.h issues I'm not sure...

You can try turning on C++ logging and see if it says anything strange. Here's my unfinished Log guide: https://github.com/boocs/Unreal-VSCode-diy-config-check-github

After you open c_cpp_properties.json and restart vscode wait for the intellisense icons to disappear. Now clear the log and switch to the file that has the error. When intellisense icons disappear copy the log and paste the pastbin.com here.

**Comment by boocs** [comment]
I edited the previous post to the correct site. Don't go to the other one 😰

**Comment by turkeys-cyber** [comment]
Thank you. I have found the cause of the error, it is a plugin called clangd confused with vscode.cpptools and intellisense can not recognize it.

**Comment by Mark-Bezyinski** [comment]
> Thank you. I have found the cause of the error, it is a plugin called clangd confused with vscode.cpptools and intellisense can not recognize it.

@turkeys-cyber 
Thank you so much!

**Comment by boocs** [comment]
I do need someone to help test my clangd extension for Mac/Mac M1. If you have time/experience then let me know. No problems if not. 

You can easily disable the clangd extension and my unreal-clangd extenson globally and only enable it per project(workspace). So it won't affect any of your other projects. You also can just create a test project based on the FPS template.

Why? clangd Intellisense is very fast and has some nice features. Way better, imo, than the Microsoft C++ extension's intellisense. You will still use Microsoft's C++ extension though for debugging.

Here's the link: https://github.com/boocs/unreal-clangd
